pushd %cd%
cd "C:\Programs\XPE40\bin"
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\01-Hierarchy\Hierarchy-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\02-RollUp\RollUp-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\03-RollForward\RollForward-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\08-TextBlock\TextBlock-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\04-CompoundFact\CompoundFact-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\05-Adjustment\Adjustment-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\06-Variance\Variance-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\09-Grid\Grid-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\07-ComplexComputation\ComplexComputation-SampleInstance.xml_FormulaTrace.xml" -l:full
 
"C:\Programs\XPE40\bin\xbrlprocessor.exe" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml_ValidationResult.xml"
"C:\Programs\XPE40\bin\xbrlCalculate" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml_CalculationTrace.xml" -v
"C:\Programs\XPE40\bin\xbrlFormula" -i:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml" -o:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\__Junk.xml" -t:"C:\Users\Charlie\Documents\CurrentVersions\DigitalFinancialReporting\Metapatterns\2017-05-07\10-RollForwardInfo\RollForwardInfo-SampleInstance.xml_FormulaTrace.xml" -l:full
 
